console.log("\t\t\t\t\t \t __                __   __\n\t\t\t\t\t\t/ _\\ __ _ _____ __ | |__| |__\n\t\t\t\t\t\t\\ \\ / _` (  __/ _ `|  _/|  __ `\\\n\t\t\t\t\t\t_\\ \\ (_| | | ( (_| | |_ | |  | |\n\t\t\t\t\t\t\\__/\\__,_|_|  \\__,_|__/ |_|  |_|");console.log("Hi, Hacker :)");console.log(":) Copyright 2014 Sarath.");var requirejs,require,define;
(function(Y){function G(b){return"[object Function]"===N.call(b)}function H(b){return"[object Array]"===N.call(b)}function x(b,c){if(b){var d;for(d=0;d<b.length&&(!b[d]||!c(b[d],d,b));d+=1);}}function O(b,c){if(b){var d;for(d=b.length-1;-1<d&&(!b[d]||!c(b[d],d,b));d-=1);}}function r(b,c){return fa.call(b,c)}function l(b,c){return r(b,c)&&b[c]}function E(b,c){for(var d in b)if(r(b,d)&&c(b[d],d))break}function P(b,c,d,h){c&&E(c,function(c,i){if(d||!r(b,i))h&&"string"!==typeof c?(b[i]||(b[i]={}),P(b[i],
c,d,h)):b[i]=c});return b}function t(b,c){return function(){return c.apply(b,arguments)}}function $(b){throw b;}function aa(b){if(!b)return b;var c=Y;x(b.split("."),function(b){c=c[b]});return c}function z(b,c,d,h){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=h;d&&(c.originalError=d);return c}function ga(b){function c(a,f,b){var e,m,c,g,d,h,i,j=f&&f.split("/"),o=k.map,n=o&&o["*"];if(a&&"."===a.charAt(0))if(f){e=l(k.pkgs,f)?j=[f]:j.slice(0,j.length-1);f=
a=e.concat(a.split("/"));for(e=0;f[e];e+=1)if(m=f[e],"."===m)f.splice(e,1),e-=1;else if(".."===m)if(1===e&&(".."===f[2]||".."===f[0]))break;else 0<e&&(f.splice(e-1,2),e-=2);e=l(k.pkgs,f=a[0]);a=a.join("/");e&&a===f+"/"+e.main&&(a=f)}else 0===a.indexOf("./")&&(a=a.substring(2));if(b&&o&&(j||n)){f=a.split("/");for(e=f.length;0<e;e-=1){c=f.slice(0,e).join("/");if(j)for(m=j.length;0<m;m-=1)if(b=l(o,j.slice(0,m).join("/")))if(b=l(b,c)){g=b;d=e;break}if(g)break;!h&&n&&l(n,c)&&(h=l(n,c),i=e)}!g&&h&&(g=h,
d=i);g&&(f.splice(0,d,g),a=f.join("/"))}return a}function d(a){y&&x(document.getElementsByTagName("script"),function(f){if(f.getAttribute("data-requiremodule")===a&&f.getAttribute("data-requirecontext")===j.contextName)return f.parentNode.removeChild(f),!0})}function h(a){var f=l(k.paths,a);if(f&&H(f)&&1<f.length)return d(a),f.shift(),j.require.undef(a),j.require([a]),!0}function Z(a){var f,b=a?a.indexOf("!"):-1;-1<b&&(f=a.substring(0,b),a=a.substring(b+1,a.length));return[f,a]}function o(a,f,b,e){var m,
A,g=null,d=f?f.name:null,h=a,i=!0,k="";a||(i=!1,a="_@r"+(N+=1));a=Z(a);g=a[0];a=a[1];g&&(g=c(g,d,e),A=l(q,g));a&&(g?k=A&&A.normalize?A.normalize(a,function(a){return c(a,d,e)}):c(a,d,e):(k=c(a,d,e),a=Z(k),g=a[0],k=a[1],b=!0,m=j.nameToUrl(k)));b=g&&!A&&!b?"_unnormalized"+(O+=1):"";return{prefix:g,name:k,parentMap:f,unnormalized:!!b,url:m,originalName:h,isDefine:i,id:(g?g+"!"+k:k)+b}}function p(a){var f=a.id,b=l(n,f);b||(b=n[f]=new j.Module(a));return b}function s(a,f,b){var e=a.id,m=l(n,e);if(r(q,
e)&&(!m||m.defineEmitComplete))"defined"===f&&b(q[e]);else if(m=p(a),m.error&&"error"===f)b(m.error);else m.on(f,b)}function u(a,f){var b=a.requireModules,e=!1;if(f)f(a);else if(x(b,function(f){if(f=l(n,f))f.error=a,f.events.error&&(e=!0,f.emit("error",a))}),!e)i.onError(a)}function v(){Q.length&&(ha.apply(F,[F.length-1,0].concat(Q)),Q=[])}function w(a){delete n[a];delete S[a]}function D(a,f,b){var e=a.map.id;a.error?a.emit("error",a.error):(f[e]=!0,x(a.depMaps,function(e,c){var g=e.id,d=l(n,g);d&&
!a.depMatched[c]&&!b[g]&&(l(f,g)?(a.defineDep(c,q[g]),a.check()):D(d,f,b))}),b[e]=!0)}function B(){var a,f,b,e,m=(b=1E3*k.waitSeconds)&&j.startTime+b<(new Date).getTime(),c=[],g=[],i=!1,l=!0;if(!T){T=!0;E(S,function(b){a=b.map;f=a.id;if(b.enabled&&(a.isDefine||g.push(b),!b.error))if(!b.inited&&m)h(f)?i=e=!0:(c.push(f),d(f));else if(!b.inited&&b.fetched&&a.isDefine&&(i=!0,!a.prefix))return l=!1});if(m&&c.length)return b=z("timeout","Load timeout for modules: "+c,null,c),b.contextName=j.contextName,
u(b);l&&x(g,function(a){D(a,{},{})});if((!m||e)&&i)if((y||ca)&&!U)U=setTimeout(function(){U=0;B()},50);T=!1}}function C(a){r(q,a[0])||p(o(a[0],null,!0)).init(a[1],a[2])}function I(a){var a=a.currentTarget||a.srcElement,b=j.onScriptLoad;a.detachEvent&&!V?a.detachEvent("onreadystatechange",b):a.removeEventListener("load",b,!1);b=j.onScriptError;(!a.detachEvent||V)&&a.removeEventListener("error",b,!1);return{node:a,id:a&&a.getAttribute("data-requiremodule")}}function J(){var a;for(v();F.length;){a=F.shift();
if(null===a[0])return u(z("mismatch","Mismatched anonymous define() module: "+a[a.length-1]));C(a)}}var T,W,j,K,U,k={waitSeconds:7,baseUrl:"./",paths:{},pkgs:{},shim:{},config:{}},n={},S={},X={},F=[],q={},R={},N=1,O=1;K={require:function(a){return a.require?a.require:a.require=j.makeRequire(a.map)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports?a.exports:a.exports=q[a.map.id]={}},module:function(a){return a.module?a.module:a.module={id:a.map.id,uri:a.map.url,config:function(){var b=
l(k.pkgs,a.map.id);return(b?l(k.config,a.map.id+"/"+b.main):l(k.config,a.map.id))||{}},exports:q[a.map.id]}}};W=function(a){this.events=l(X,a.id)||{};this.map=a;this.shim=l(k.shim,a.id);this.depExports=[];this.depMaps=[];this.depMatched=[];this.pluginMaps={};this.depCount=0};W.prototype={init:function(a,b,c,e){e=e||{};if(!this.inited){this.factory=b;if(c)this.on("error",c);else this.events.error&&(c=t(this,function(a){this.emit("error",a)}));this.depMaps=a&&a.slice(0);this.errback=c;this.inited=!0;
this.ignore=e.ignore;e.enabled||this.enabled?this.enable():this.check()}},defineDep:function(a,b){this.depMatched[a]||(this.depMatched[a]=!0,this.depCount-=1,this.depExports[a]=b)},fetch:function(){if(!this.fetched){this.fetched=!0;j.startTime=(new Date).getTime();var a=this.map;if(this.shim)j.makeRequire(this.map,{enableBuildCallback:!0})(this.shim.deps||[],t(this,function(){return a.prefix?this.callPlugin():this.load()}));else return a.prefix?this.callPlugin():this.load()}},load:function(){var a=
this.map.url;R[a]||(R[a]=!0,j.load(this.map.id,a))},check:function(){if(this.enabled&&!this.enabling){var a,b,c=this.map.id;b=this.depExports;var e=this.exports,m=this.factory;if(this.inited)if(this.error)this.emit("error",this.error);else{if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(G(m)){if(this.events.error&&this.map.isDefine||i.onError!==$)try{e=j.execCb(c,m,b,e)}catch(d){a=d}else e=j.execCb(c,m,b,e);this.map.isDefine&&((b=this.module)&&void 0!==b.exports&&b.exports!==
this.exports?e=b.exports:void 0===e&&this.usingExports&&(e=this.exports));if(a)return a.requireMap=this.map,a.requireModules=this.map.isDefine?[this.map.id]:null,a.requireType=this.map.isDefine?"define":"require",u(this.error=a)}else e=m;this.exports=e;if(this.map.isDefine&&!this.ignore&&(q[c]=e,i.onResourceLoad))i.onResourceLoad(j,this.map,this.depMaps);w(c);this.defined=!0}this.defining=!1;this.defined&&!this.defineEmitted&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=
!0)}}else this.fetch()}},callPlugin:function(){var a=this.map,b=a.id,d=o(a.prefix);this.depMaps.push(d);s(d,"defined",t(this,function(e){var m,d;d=this.map.name;var g=this.map.parentMap?this.map.parentMap.name:null,h=j.makeRequire(a.parentMap,{enableBuildCallback:!0});if(this.map.unnormalized){if(e.normalize&&(d=e.normalize(d,function(a){return c(a,g,!0)})||""),e=o(a.prefix+"!"+d,this.map.parentMap),s(e,"defined",t(this,function(a){this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),
d=l(n,e.id)){this.depMaps.push(e);if(this.events.error)d.on("error",t(this,function(a){this.emit("error",a)}));d.enable()}}else m=t(this,function(a){this.init([],function(){return a},null,{enabled:!0})}),m.error=t(this,function(a){this.inited=!0;this.error=a;a.requireModules=[b];E(n,function(a){0===a.map.id.indexOf(b+"_unnormalized")&&w(a.map.id)});u(a)}),m.fromText=t(this,function(e,c){var d=a.name,g=o(d),A=L;c&&(e=c);A&&(L=!1);p(g);r(k.config,b)&&(k.config[d]=k.config[b]);try{i.exec(e)}catch(ba){return u(z("fromtexteval",
"fromText eval for "+b+" failed: "+ba,ba,[b]))}A&&(L=!0);this.depMaps.push(g);j.completeLoad(d);h([d],m)}),e.load(a.name,h,m,k)}));j.enable(d,this);this.pluginMaps[d.id]=d},enable:function(){S[this.map.id]=this;this.enabling=this.enabled=!0;x(this.depMaps,t(this,function(a,b){var c,e;if("string"===typeof a){a=o(a,this.map.isDefine?this.map:this.map.parentMap,!1,!this.skipMap);this.depMaps[b]=a;if(c=l(K,a.id)){this.depExports[b]=c(this);return}this.depCount+=1;s(a,"defined",t(this,function(a){this.defineDep(b,
a);this.check()}));this.errback&&s(a,"error",t(this,this.errback))}c=a.id;e=n[c];!r(K,c)&&e&&!e.enabled&&j.enable(a,this)}));E(this.pluginMaps,t(this,function(a){var b=l(n,a.id);b&&!b.enabled&&j.enable(a,this)}));this.enabling=!1;this.check()},on:function(a,b){var c=this.events[a];c||(c=this.events[a]=[]);c.push(b)},emit:function(a,b){x(this.events[a],function(a){a(b)});"error"===a&&delete this.events[a]}};j={config:k,contextName:b,registry:n,defined:q,urlFetched:R,defQueue:F,Module:W,makeModuleMap:o,
nextTick:i.nextTick,onError:u,configure:function(a){a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");var b=k.pkgs,c=k.shim,e={paths:!0,config:!0,map:!0};E(a,function(a,b){e[b]?"map"===b?(k.map||(k.map={}),P(k[b],a,!0,!0)):P(k[b],a,!0):k[b]=a});a.shim&&(E(a.shim,function(a,b){H(a)&&(a={deps:a});if((a.exports||a.init)&&!a.exportsFn)a.exportsFn=j.makeShimExports(a);c[b]=a}),k.shim=c);a.packages&&(x(a.packages,function(a){a="string"===typeof a?{name:a}:a;b[a.name]={name:a.name,
location:a.location||a.name,main:(a.main||"main").replace(ia,"").replace(da,"")}}),k.pkgs=b);E(n,function(a,b){!a.inited&&!a.map.unnormalized&&(a.map=o(b))});if(a.deps||a.callback)j.require(a.deps||[],a.callback)},makeShimExports:function(a){return function(){var b;a.init&&(b=a.init.apply(Y,arguments));return b||a.exports&&aa(a.exports)}},makeRequire:function(a,f){function d(e,c,h){var g,k;f.enableBuildCallback&&c&&G(c)&&(c.__requireJsBuild=!0);if("string"===typeof e){if(G(c))return u(z("requireargs",
"Invalid require call"),h);if(a&&r(K,e))return K[e](n[a.id]);if(i.get)return i.get(j,e,a,d);g=o(e,a,!1,!0);g=g.id;return!r(q,g)?u(z("notloaded",'Module name "'+g+'" has not been loaded yet for context: '+b+(a?"":". Use require([])"))):q[g]}J();j.nextTick(function(){J();k=p(o(null,a));k.skipMap=f.skipMap;k.init(e,c,h,{enabled:!0});B()});return d}f=f||{};P(d,{isBrowser:y,toUrl:function(b){var f,d=b.lastIndexOf("."),g=b.split("/")[0];if(-1!==d&&(!("."===g||".."===g)||1<d))f=b.substring(d,b.length),b=
b.substring(0,d);return j.nameToUrl(c(b,a&&a.id,!0),f,!0)},defined:function(b){return r(q,o(b,a,!1,!0).id)},specified:function(b){b=o(b,a,!1,!0).id;return r(q,b)||r(n,b)}});a||(d.undef=function(b){v();var c=o(b,a,!0),d=l(n,b);delete q[b];delete R[c.url];delete X[b];d&&(d.events.defined&&(X[b]=d.events),w(b))});return d},enable:function(a){l(n,a.id)&&p(a).enable()},completeLoad:function(a){var b,c,d=l(k.shim,a)||{},i=d.exports;for(v();F.length;){c=F.shift();if(null===c[0]){c[0]=a;if(b)break;b=!0}else c[0]===
a&&(b=!0);C(c)}c=l(n,a);if(!b&&!r(q,a)&&c&&!c.inited){if(k.enforceDefine&&(!i||!aa(i)))return h(a)?void 0:u(z("nodefine","No define call for "+a,null,[a]));C([a,d.deps||[],d.exportsFn])}B()},nameToUrl:function(a,b,c){var d,h,j,g,o,n;if(i.jsExtRegExp.test(a))g=a+(b||"");else{d=k.paths;h=k.pkgs;g=a.split("/");for(o=g.length;0<o;o-=1)if(n=g.slice(0,o).join("/"),j=l(h,n),n=l(d,n)){H(n)&&(n=n[0]);g.splice(0,o,n);break}else if(j){a=a===j.name?j.location+"/"+j.main:j.location;g.splice(0,o,a);break}g=g.join("/");
g+=b||(/\?/.test(g)||c?"":".js");g=("/"===g.charAt(0)||g.match(/^[\w\+\.\-]+:/)?"":k.baseUrl)+g}return k.urlArgs?g+((-1===g.indexOf("?")?"?":"&")+k.urlArgs):g},load:function(a,b){i.load(j,a,b)},execCb:function(a,b,c,d){return b.apply(d,c)},onScriptLoad:function(a){if("load"===a.type||ja.test((a.currentTarget||a.srcElement).readyState))M=null,a=I(a),j.completeLoad(a.id)},onScriptError:function(a){var b=I(a);if(!h(b.id))return u(z("scripterror","Script error for: "+b.id,a,[b.id]))}};j.require=j.makeRequire();
return j}var i,v,w,B,I,C,M,J,p,ea,ka=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,la=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,da=/\.js$/,ia=/^\.\//;v=Object.prototype;var N=v.toString,fa=v.hasOwnProperty,ha=Array.prototype.splice,y=!!("undefined"!==typeof window&&navigator&&window.document),ca=!y&&"undefined"!==typeof importScripts,ja=y&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,V="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),D={},s={},Q=[],L=
!1;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(G(requirejs))return;s=requirejs;requirejs=void 0}"undefined"!==typeof require&&!G(require)&&(s=require,require=void 0);i=requirejs=function(b,c,d,h){var p,o="_";!H(b)&&"string"!==typeof b&&(p=b,H(c)?(b=c,c=d,d=h):b=[]);p&&p.context&&(o=p.context);(h=l(D,o))||(h=D[o]=i.s.newContext(o));p&&h.configure(p);return h.require(b,c,d)};i.config=function(b){return i(b)};i.nextTick="undefined"!==typeof setTimeout?function(b){setTimeout(b,
4)}:function(b){b()};require||(require=i);i.version="2.1.8";i.jsExtRegExp=/^\/|:|\?|\.js$/;i.isBrowser=y;v=i.s={contexts:D,newContext:ga};i({});x(["toUrl","undef","defined","specified"],function(b){i[b]=function(){var c=D._;return c.require[b].apply(c,arguments)}});if(y&&(w=v.head=document.getElementsByTagName("head")[0],B=document.getElementsByTagName("base")[0]))w=v.head=B.parentNode;i.onError=$;i.createNode=function(b){var c=b.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):
document.createElement("script");c.type=b.scriptType||"text/javascript";c.charset="utf-8";c.async=!0;return c};i.load=function(b,c,d){var h=b&&b.config||{};if(y)return h=i.createNode(h,c,d),h.setAttribute("data-requirecontext",b.contextName),h.setAttribute("data-requiremodule",c),h.attachEvent&&!(h.attachEvent.toString&&0>h.attachEvent.toString().indexOf("[native code"))&&!V?(L=!0,h.attachEvent("onreadystatechange",b.onScriptLoad)):(h.addEventListener("load",b.onScriptLoad,!1),h.addEventListener("error",
b.onScriptError,!1)),h.src=d,J=h,B?w.insertBefore(h,B):w.appendChild(h),J=null,h;if(ca)try{importScripts(d),b.completeLoad(c)}catch(l){b.onError(z("importscripts","importScripts failed for "+c+" at "+d,l,[c]))}};y&&O(document.getElementsByTagName("script"),function(b){w||(w=b.parentNode);if(I=b.getAttribute("data-main"))return p=I,s.baseUrl||(C=p.split("/"),p=C.pop(),ea=C.length?C.join("/")+"/":"./",s.baseUrl=ea),p=p.replace(da,""),i.jsExtRegExp.test(p)&&(p=I),s.deps=s.deps?s.deps.concat(p):[p],!0});
define=function(b,c,d){var h,i;"string"!==typeof b&&(d=c,c=b,b=null);H(c)||(d=c,c=null);!c&&G(d)&&(c=[],d.length&&(d.toString().replace(ka,"").replace(la,function(b,d){c.push(d)}),c=(1===d.length?["require"]:["require","exports","module"]).concat(c)));if(L){if(!(h=J))M&&"interactive"===M.readyState||O(document.getElementsByTagName("script"),function(b){if("interactive"===b.readyState)return M=b}),h=M;h&&(b||(b=h.getAttribute("data-requiremodule")),i=D[h.getAttribute("data-requirecontext")])}(i?i.defQueue:
Q).push([b,c,d])};define.amd={jQuery:!0};i.exec=function(b){return eval(b)};i(s)}})(this);
